name: DFMDock
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libsqlite=3.46.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - python=3.10.14
  - readline=8.2
  - setuptools=74.1.2
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - dm-tree==0.1.8
      - einops==0.8.0
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - hydra-core==1.3.2
      - idna==3.10
      - jinja2==3.1.3
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - packaging==24.1
      - pillow==10.2.0
      - psutil==6.0.0
      - pyparsing==3.1.4
      - pytorch-lightning==2.4.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.14.1
      - sympy==1.12
      - torch==2.4.1+cu118
      - torch-geometric==2.6.0
      - torchaudio==2.4.1+cu118
      - torchmetrics==1.4.2
      - torchvision==0.19.1+cu118
      - tqdm==4.66.5
      - triton==3.0.0
      - typing-extensions==4.9.0
      - urllib3==2.2.3
      - yarl==1.11.1
