_target_: models.DFMDock_1.DFMDock

model:
  lm_embed_dim: 1301 # 1280 (ESM) + 21 (One-Hot) 
  positional_embed_dim: 66 # 66 (Residue)
  spatial_embed_dim: 100 # 40 (dist) + 24 (phi) + 24 (psi) + 12 (omega) 
  node_dim: 256
  edge_dim: 128
  inner_dim: 128
  depth: 6
  dropout: 0.1
  cut_off: 20.0
  normalize: True
  agg: 'mean'

diffuser:
  r3:
    min_sigma: 0.1
    max_sigma: 30.0
    schedule: VE
  so3:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: logarithmic
    cache_dir: .cache/
    use_cached_score: False
    
experiment:
  lr: 1e-4
  weight_decay: 0.0
  perturb_tr: True
  perturb_rot: True
  separate_energy_loss: True
  separate_tr_loss: True
  separate_rot_loss: True
  grad_energy: False
  use_contrastive_loss: False
  use_contact_loss: False
  use_interface_loss: False
  use_confidence_loss: False

