_target_: models.force_model.Force_Model

model:
  lm_embed_dim: 1301 # 1280 (ESM) + 21 (One-Hot) 
  positional_embed_dim: 66 # 66 (Residue)
  spatial_embed_dim: 25 # 16 (dist) + 3 (direct) + 6 (orient)
  node_dim: 256
  edge_dim: 128
  inner_dim: 128
  depth: 6
  dropout: 0.1
  cut_off: 20.0
  normalize: True

diffuser:
  r3:
    min_sigma: 0.1
    max_sigma: 30.0
    schedule: VE
  so3:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: logarithmic
    cache_dir: .cache/
    use_cached_score: False
    
experiment:
  lr: 1e-4
  weight_decay: 0.0
  perturb_tr: True
  perturb_rot: True
  separate_tr_loss: True
  separate_rot_loss: True
  use_interface_loss: True
  use_contrastive_loss: False

